### PR TITLE
Radius and Eccentricity

### PR DESCRIPTION
**Pull request by hcars**
### Modifications:
(new algorithms, added tests or documentation)
 * Adds an eccentricity method.
 * Adds a radius method.

### Impacted submodules:
(e.g. `sknetwork.topology`)
 * sknetwork.path

### This pull request:
(your PR must match these criteria before review)
- [x] **targets the `develop` branch**
- [x] **does not decrease code coverage**
- [x] **passes the tests**
- [x] **is documented** and **the documentation build passes**
- [x] **has PEP8-compliant code** and **explicit variable naming**
- [ ] **has a tutorial** (facultative but recommended)

*Any doubts about some technicalities? Do not hesitate to look at the [dedicated Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Contributing-guide).*

### CODE REVIEW

**Comment by QLutz** [comment]
Hello,

Thank you for contributing!

We appreciate the functionalities you've added and would like you to make a few adjustments and corrections before we can merge your branch:
 * for `radius`, add a parameter `n_sources` similar to that present in the `diameter` function. That will make it possible to have an approximation even on large graphs.
 * still in `radius`, rather than using the `eccentricity` function and `map`, compute all distances between from all sources at once to enable faster computations (as the parallelism will be more efficient). Then take the max of each line and finally the min of those maxima.
 * update the docs in the `docs/` folder (have a glance at the [Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Producing-documentation#rst-files) for indications)
 * update the docstrings of each function by adding examples (or at least removing the empty sections for examples)

**Comment by QLutz** [comment]
I've also made some corrections for the function names we were in the process of making.

Beware of PEP8 styling. In particular, no line in the code should be more than 120 characters long.

**Comment by hcars** [comment]
I addressed the first 3 of your bullets. I added the methods to the path.rst file, but I'm not sure if that's sufficient.

**Comment by QLutz** [comment]
Thank you for your corrections. The last few steps before merging are the following:
 * I added your name to the AUTHORS and HISTORY files. Make sure that the spelling is correct.
 * I recently added a code coverage test. It currently does not pass. Please add a test for the exception handling you added in the `get_distances` function (in both the `n_jobs == 1` and `n_jobs > 1` cases).

**Comment by hcars** [comment]
You're welcome! I just added checks for those.

**Pull request merged**
