### PR TITLE
Betweenness centrality

### PR DESCRIPTION
**Pull request by TiphaineV**
Hi,

This is my first code contribution to sknetwork, so, sorry in advance if the code does not match the guidelines. I have done my best to follow them, and of course will make modifications accordingly. :)
For example, I am unsure about how to check that I do not decrease code coverage.

### Modifications:
 * New algorithm to compute betweenness centrality (following Brandes's algorithm)
 * Added tests and documentation for the new algorithm

### Impacted submodules:
 * `sknetwork.ranking`

### This pull request:
(your PR must match these criteria before review)
- [x] **does not decrease code coverage**
- [x] **passes the tests**
- [x] **is documented** and **the documentation build passes**
- [x] **has PEP8-compliant code** and **explicit variable naming**
- [ ] **has a tutorial** (facultative but recommended)

*Any doubts about some technicalities? Do not hesitate to look at the [dedicated Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Contributing-guide).*

### CODE REVIEW

**Comment by QLutz** [comment]
Hi Tiphaine,

Thanks for your involvement! You have 2 ways of checking coverage:
 * the lazy but long way: waiting for Travis and Codecov to do their jobs (rather long for pull requests as we check that wheels can be built, so it takes up to 45 minutes) then Codecov should comment automatically on this PR (as can be seen above). The upside is you have nothing to do except commit functional code.
 * the active way: in your terminal, at the root of the project, run `py.test --cov --doctest-modules sknetwork/`. I pushed a slight modification just now on our branch so it should work fine.

Thanks for pointing this out, I've added this to the [Wiki](https://github.com/sknetwork-team/scikit-network/wiki/Contributing-guide) for future reference.

Looking at your code, there are still a few things to consider:
 * inheritance from `BaseRanking` grants a few things to your `Betweenness` class:  

    - the attribute `self.scores_` is initialised by calling the mother class' `__init__`. For API consistency, it should play the role of your `self.betweenness_values_` attribute.


    - you do not have to code the `fit_transform` method again once `self.betweenness_values` is changed to `self.scores_` it is already taken care of by the mother class.

   
 * finding the neighbours of node `i` can be done easily thanks to the CSR format as: `neighbours = indices[indptr[i]:indptr[i+1]]` where `indices = adjacency.indices` and `indptr = adjacency.indptr`.

If any of this is not clear to you, please do tell us.

Thanks again!

**Comment by TiphaineV** [comment]
Hi Quentin,

Thanks a lot for taking the time to write detailed feedback! I'll make the changes you described, add tests for coverage, and push likely tomorrow.

Cheers!

**Comment by nathandelara** [comment]
Hi Tiphaine !
Once again, we are so glad to have you on board.

Would you be so kind to put the exact reference of the paper you are implementing in the dedicated module of the docstring ?
You can use `katz.py` as an example for this.
This will help the future users (and the reviewers) to understand your code.

Besides, it seems that the algorithm begins with a BFS, is that correct?
If it is indeed the case, there is already some efficient code in the package for this:
`sknetwork.path.search.breadth_first_search`
Ideally, we would try to leverage this in order to get a betweenness code as compact as possible.

Finally, do not forget to credit yourself !
Please modify:
* HISTORY.rst by adding the algorithm you implemented with your name between parenthesis
* AUTHORS.rst which is supposed to be sorted alphabetically.

Best

**Comment by TiphaineV** [comment]
Hi Nathan,

Thanks! I'll make the modifications you suggest; for reference, the implementation I follow is the one from Brandes [1] 
There a more novel ref, that includes endpoints in shortest path computations, as well as normalization [2], but i'd rather start with the "bare bones" algorithm and then make amendments when I feel fully comfortable with the PR process and the guidelines. (Note that the basic algorithm is the same in both refs, of course). 

I've seen the BFS already implemented in `scikit-network`, however in this cas I rely on a modified BFS (that allows me to keep track of the nodes I have already seen, and on which path; this is the goal of the stack `S`, the `dists` and `sigma` variables; that way, I can then empty the stack and use the values from the forward phase to accumulate the betweenness values in the backtracking phase. Because of this, I don't think I can rely on the already implemented BFS, or, more precisely, relying on it would require going through the result to re-build the paths, which is inefficient. Does that make sense? 

Cheers,

PS: congratulations for your defense! It was a very interesting talk :) 
[1] https://kops.uni-konstanz.de/bitstream/handle/123456789/5739/algorithm.pdf
[2] https://www.sciencedirect.com/science/article/pii/S0378873307000731

**Comment by TiphaineV** [comment]
Hi everyone,
So, I did the check for bigraphs as we discussed (just added a test), and converted my code to cython code. However, upon compilation of the .pyx, I get this error : 
```
copying build/lib.linux-x86_64-3.8/sknetwork/ranking/betweenness.cpython-38-x86_64-linux-gnu.so -> sknetwork/ranking
error: could not create 'sknetwork/ranking/betweenness.cpython-38-x86_64-linux-gnu.so': No such file or directory
```
Here's my (test) `setup.py` : 
```python
from setuptools import setup
from Cython.Build import cythonize
from distutils.extension import Extension

extensions = [
    Extension("betweenness", sources=["betweenness.pyx"], extra_compile_args=["-O3"], language="c++")
]

setup(
    ext_modules = cythonize("betweenness.pyx")
)
```


I tried to look a bit around, but to no avail; is it something you're familiar with? I'll continue searching tomorrow :)
Cheers,

**Comment by tbonald** [comment]
Hi,
You don't have to modify setup.py.
Just cythonize your code (.py -> .pyx) and run the following command in a Terminal (e.g., through PyCharm):
python setup.py build_ext --inplace

I hope it helps.
Thomas

**Comment by TiphaineV** [comment]
Thanks @tbonald! It helps indeed. Now I realized the tests have to be cythonized too, I'll do this as soon as in can, then commit + push

**Comment by TiphaineV** [comment]
Hi again,

I'm sorry, I have one last issue with tests and coverage... I can run coverage, however `betweenness.pyx` is systematically excluded of the cov report (my test file appears and is tested, just not the `pyx` file. 

My header in `betweenness.pyx`:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# distutils: language = c++
# cython: language_level=3
# cython: linetrace=True
# distutils: define_macros=CYTHON_TRACE_NOGIL=1
```

And I used `make test` then `make coverage` to get the reports. Have I missed something, in conf files maybe?

**Comment by QLutz** [comment]
Hi Tiphaine,

I've made a pull request from develop to your branch so you can benefit from some minor corrections we've made lately (in particular a timeout for Konect). If the CI gives it the green light, please merge it on your forked repo.

Then, you may try dropping the first 2 lines in your header, i.e. change it to just:
```
# distutils: language = c++
# cython: language_level=3
# cython: linetrace=True
# distutils: define_macros=CYTHON_TRACE_NOGIL=1
```
This appears to work on my end.

**Comment by TiphaineV** [comment]
Hi @QLutz , I did this; I think we can ignore the coverage outcries (which are unrelated to my code); if we follow the rules, then it should be @tbonald that merges the code to the main branch?

**Comment by QLutz** [comment]
I think you are right on both accounts. Did you have any chance to measure the speed-up with Cython?

**Comment by TiphaineV** [comment]
Let me check that actually :)

**Pull request merged**
